### ISSUE TITLE
Sub buttons are visible in other tabs

### ISSUE THREAD

**Issue by newajthevillager** [rjsvieira/floatingMenu#12]
I have several tabs in my activity. If I open the `FloatingMenuButton` and move to other tabs, the sub buttons are visible there. Is there any method like this : `setClosedOnTouchOutside(true`) ?

**Comment by hiramcastrod** [comment]
i got the same problem, when i navigate thru fragments

**Comment by rjsvieira** [comment]
Hello @newajthevillager 
I assume your tabs are fragments and therefore belong to the same activity. 
If so, you can put the floatingMenuButton on the activity and have it shared on the fragments or you can place the floatingMenuButton inside the fragment and it wont be shared to the others.
My advice is that you either close it with the "closeMenu()" function or simple hide/show it depending on the fragments you need.

**Comment by hiramcastrod** [comment]
i solved the problem : 
  @Override
    public void onPause() {
        FloatingMenuButton.closeMenu();
        super.onPause();
    }
this makes the menu closes when you change to another fragment

**Comment by rjsvieira** [comment]
Hello @hiramcastrod @newajthevillager 
You can also attach a TabChangedListener and detect whenever the tab changes in order to close it.
The FloatingMenuButton was created into order to survive fragment transitions so it would serve as a tooltip button for the whole activity.
Glad you found out a solution.
Regards,

**Comment by LukasAnda** [comment]
Hello, how do I implement this with ViewPager ? I am using the floating menu inside each fragment and can not use it in the activity itself

**Comment by rjsvieira** [comment]
Hello @LukasAnda 
So, you have one floating action button on each fragment? Or one floating action button shared between fragments?

Regards,
