### ISSUE TITLE
Feature Request: How to prevent the control from dragging and changing position

### ISSUE THREAD

**Issue by lamiajoyee** [rjsvieira/floatingMenu#2]
It is my requirement to prevent the FloatingMenuButton from being dragged and moved. Is there any easy way to do so other than overriding/propagating touch events?

**Comment by rjsvieira** [comment]
At the moment, there is no feature that prevents the button from being repositioned. Nonetheless, that can be developed with ease. I will add it to the todo list and implement it as soon as possible. I will inform you when such feature is ready.

**Comment by lamiajoyee** [comment]
As
> that can be developed with ease

I hope it would be implemented ASAP as I am badly in need of this feature

**Comment by rjsvieira** [comment]
I will try and implement it by the end of the day

**Comment by rjsvieira** [comment]
Hello @lamiajoyee 
The new 'anchored' feature has been added. Please check the new xml snippet and documentation on the READ.me file and see if it fits your needs. Thank you for the feature suggestion.

Regards,

**Comment by rjsvieira** [comment]
Also, I have not yet deployed the new change to a version on jitpack. Are you the code directly or the jitpack 1.0.0 dependency?

**Comment by lamiajoyee** [comment]
I am using the 1.0.0 jitpack

**Comment by rjsvieira** [comment]
I will release the 1.1.0 version with the change later today. Make sure to change the jitpack to 1.1.0

**Comment by rjsvieira** [comment]
Hello @lamiajoyee 
The release has been done. You can now try it on 1.1.0
Regards,

**Comment by lamiajoyee** [comment]
Nice implementation, I am closing the issue
