### ISSUE TITLE
I can't get the library

### ISSUE THREAD

**Issue by mengdd** [rjsvieira/floatingMenu#3]
I followed the guide in README.
In `root/build.gradle`
```
allprojects {
  repositories {
  ...
  maven { url 'https://jitpack.io' }
  }
}
``` 
In `app/build.gradle`
```
dependencies {
  compile 'com.github.rjsvieira:FloatingMenuButton:1.1.0'
}
```

But I got this after sync: "Failed to resolve: com.github.rjsvieira:FloatingMenuButton:1.1.0".

**Comment by rjsvieira** [comment]
Hello @mengdd ,

The code snippet of the dependency on the Read.ME file was wrong. 
The correct dependency is :
```groovy
 compile 'com.github.rjsvieira:floatingMenu:1.1.0'
```

I have fixed it. Thank you for pointing it out.
Regards,

**Comment by mengdd** [comment]
@rjsvieira got it, thanks~
