### ISSUE TITLE
SubButton onClickListener

### ISSUE THREAD

**Issue by brunopaolo** [rjsvieira/floatingMenu#4]
Hi

I have a fragment and when I try to find subbutton for set onClickListener the findViewById return null.

        sub_button_1 = (FloatingSubButton) rootView.findViewById(R.id.sub_button_1);
        sub_button_1.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
            }
        });

Can you help me ?

Thanks in advance 
Paolo

**Comment by rjsvieira** [comment]
Hello @brunopaolo 
I can think of 2 instances where that can happen : 
Have you tried finding the view through to do  :
**floatingButton.findViewById(R.id.sub_button_1)** ; ?

Regards,

**Comment by brunopaolo** [comment]
floatingButton.findViewById(R.id.sub_button_1) ; ?

Yes I have already tried it , but the result is always null.
Actually I have found a workaround using android:onClick="onButtonClick" in xml file layout.
do you think can be good for your plugin ?

KR
Paolo

**Comment by rjsvieira** [comment]
Hello again @brunopaolo 
Can you try and open the FloatingMenu before trying to set the clickListener?
Regards,

**Comment by rjsvieira** [comment]
Hello @brunopaolo 
Never quite heard from you regarding this issue. Can I close the ticket?
Regards,
